
service: weather-app-backend
plugins:
  - serverless-dotenv-plugin
org: pack-an-umbrella 

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment:
     API_KEY: ${file(./config.${self:provider.stage}.json):db_host}


# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

functions:
  weather: 
    handler: handler.weather
    events:
      - http:
         path: weather
         method: get
         cors: true
# 
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#    